// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.3
// source: admin_movies_service_v1_messages.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMovieRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MovieID int32 `protobuf:"varint,1,opt,name=movieID,json=movie_id,proto3" json:"movieID,omitempty"`
}

func (x *GetMovieRequest) Reset() {
	*x = GetMovieRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_service_v1_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieRequest) ProtoMessage() {}

func (x *GetMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_service_v1_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieRequest.ProtoReflect.Descriptor instead.
func (*GetMovieRequest) Descriptor() ([]byte, []int) {
	return file_admin_movies_service_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *GetMovieRequest) GetMovieID() int32 {
	if x != nil {
		return x.MovieID
	}
	return 0
}

// for multiple values use ',' separator
type GetMoviesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MoviesIDs    *string `protobuf:"bytes,1,opt,name=moviesIDs,json=movies_ids,proto3,oneof" json:"moviesIDs,omitempty"`
	GenresIDs    *string `protobuf:"bytes,2,opt,name=genresIDs,json=genres_ids,proto3,oneof" json:"genresIDs,omitempty"`
	CountriesIDs *string `protobuf:"bytes,3,opt,name=countriesIDs,json=country_ids,proto3,oneof" json:"countriesIDs,omitempty"`
	Title        *string `protobuf:"bytes,4,opt,name=title,proto3,oneof" json:"title,omitempty"`
	AgeRatings   *string `protobuf:"bytes,5,opt,name=ageRatings,json=age_ratings,proto3,oneof" json:"ageRatings,omitempty"`
	// if limit = 0, will be used default limit = 10, if bigger than 100, will be used max limit = 100
	Limit  uint32 `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset uint32 `protobuf:"varint,7,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *GetMoviesRequest) Reset() {
	*x = GetMoviesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_service_v1_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMoviesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMoviesRequest) ProtoMessage() {}

func (x *GetMoviesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_service_v1_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMoviesRequest.ProtoReflect.Descriptor instead.
func (*GetMoviesRequest) Descriptor() ([]byte, []int) {
	return file_admin_movies_service_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *GetMoviesRequest) GetMoviesIDs() string {
	if x != nil && x.MoviesIDs != nil {
		return *x.MoviesIDs
	}
	return ""
}

func (x *GetMoviesRequest) GetGenresIDs() string {
	if x != nil && x.GenresIDs != nil {
		return *x.GenresIDs
	}
	return ""
}

func (x *GetMoviesRequest) GetCountriesIDs() string {
	if x != nil && x.CountriesIDs != nil {
		return *x.CountriesIDs
	}
	return ""
}

func (x *GetMoviesRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *GetMoviesRequest) GetAgeRatings() string {
	if x != nil && x.AgeRatings != nil {
		return *x.AgeRatings
	}
	return ""
}

func (x *GetMoviesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetMoviesRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type CreateMovieRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description      string  `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	ShortDescription string  `protobuf:"bytes,2,opt,name=shortDescription,json=short_description,proto3" json:"shortDescription,omitempty"`
	TitleRU          string  `protobuf:"bytes,3,opt,name=titleRU,json=title_ru,proto3" json:"titleRU,omitempty"`
	TitleEN          *string `protobuf:"bytes,4,opt,name=titleEN,json=title_en,proto3,oneof" json:"titleEN,omitempty"`
	GenresIDs        []int32 `protobuf:"varint,5,rep,packed,name=genresIDs,json=genres_ids,proto3" json:"genresIDs,omitempty"`
	// movie duration in minutes
	Duration      int32   `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`
	CountriesIDs  []int32 `protobuf:"varint,7,rep,packed,name=countriesIDs,json=country_ids,proto3" json:"countriesIDs,omitempty"`
	Poster        []byte  `protobuf:"bytes,8,opt,name=poster,proto3" json:"poster,omitempty"`
	PreviewPoster []byte  `protobuf:"bytes,9,opt,name=previewPoster,json=preview_poster,proto3" json:"previewPoster,omitempty"`
	Background    []byte  `protobuf:"bytes,10,opt,name=background,proto3" json:"background,omitempty"`
	ReleaseYear   int32   `protobuf:"varint,11,opt,name=releaseYear,json=release_year,proto3" json:"releaseYear,omitempty"`
	AgeRating     string  `protobuf:"bytes,12,opt,name=ageRating,json=age_rating,proto3" json:"ageRating,omitempty"`
}

func (x *CreateMovieRequest) Reset() {
	*x = CreateMovieRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_service_v1_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMovieRequest) ProtoMessage() {}

func (x *CreateMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_service_v1_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMovieRequest.ProtoReflect.Descriptor instead.
func (*CreateMovieRequest) Descriptor() ([]byte, []int) {
	return file_admin_movies_service_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMovieRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateMovieRequest) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *CreateMovieRequest) GetTitleRU() string {
	if x != nil {
		return x.TitleRU
	}
	return ""
}

func (x *CreateMovieRequest) GetTitleEN() string {
	if x != nil && x.TitleEN != nil {
		return *x.TitleEN
	}
	return ""
}

func (x *CreateMovieRequest) GetGenresIDs() []int32 {
	if x != nil {
		return x.GenresIDs
	}
	return nil
}

func (x *CreateMovieRequest) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *CreateMovieRequest) GetCountriesIDs() []int32 {
	if x != nil {
		return x.CountriesIDs
	}
	return nil
}

func (x *CreateMovieRequest) GetPoster() []byte {
	if x != nil {
		return x.Poster
	}
	return nil
}

func (x *CreateMovieRequest) GetPreviewPoster() []byte {
	if x != nil {
		return x.PreviewPoster
	}
	return nil
}

func (x *CreateMovieRequest) GetBackground() []byte {
	if x != nil {
		return x.Background
	}
	return nil
}

func (x *CreateMovieRequest) GetReleaseYear() int32 {
	if x != nil {
		return x.ReleaseYear
	}
	return 0
}

func (x *CreateMovieRequest) GetAgeRating() string {
	if x != nil {
		return x.AgeRating
	}
	return ""
}

type UpdateMovieRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MovieID          int32   `protobuf:"varint,1,opt,name=movieID,json=movie_id,proto3" json:"movieID,omitempty"`
	Description      *string `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	ShortDescription *string `protobuf:"bytes,3,opt,name=shortDescription,json=short_description,proto3,oneof" json:"shortDescription,omitempty"`
	TitleRU          *string `protobuf:"bytes,4,opt,name=titleRU,json=title_ru,proto3,oneof" json:"titleRU,omitempty"`
	TitleEN          *string `protobuf:"bytes,5,opt,name=titleEN,json=title_en,proto3,oneof" json:"titleEN,omitempty"`
	GenresIDs        []int32 `protobuf:"varint,6,rep,packed,name=genresIDs,json=genres_ids,proto3" json:"genresIDs,omitempty"`
	UpdateGenres     bool    `protobuf:"varint,7,opt,name=updateGenres,json=update_genres,proto3" json:"updateGenres,omitempty"`
	// movie duration in minutes
	Duration        *int32  `protobuf:"varint,8,opt,name=duration,proto3,oneof" json:"duration,omitempty"`
	CountriesIDs    []int32 `protobuf:"varint,9,rep,packed,name=countriesIDs,json=countries_ids,proto3" json:"countriesIDs,omitempty"`
	UpdateCountries bool    `protobuf:"varint,10,opt,name=UpdateCountries,json=update_countries,proto3" json:"UpdateCountries,omitempty"`
	ReleaseYear     *int32  `protobuf:"varint,11,opt,name=releaseYear,json=release_year,proto3,oneof" json:"releaseYear,omitempty"`
	AgeRating       *string `protobuf:"bytes,12,opt,name=ageRating,json=age_rating,proto3,oneof" json:"ageRating,omitempty"`
}

func (x *UpdateMovieRequest) Reset() {
	*x = UpdateMovieRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_service_v1_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMovieRequest) ProtoMessage() {}

func (x *UpdateMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_service_v1_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMovieRequest.ProtoReflect.Descriptor instead.
func (*UpdateMovieRequest) Descriptor() ([]byte, []int) {
	return file_admin_movies_service_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMovieRequest) GetMovieID() int32 {
	if x != nil {
		return x.MovieID
	}
	return 0
}

func (x *UpdateMovieRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateMovieRequest) GetShortDescription() string {
	if x != nil && x.ShortDescription != nil {
		return *x.ShortDescription
	}
	return ""
}

func (x *UpdateMovieRequest) GetTitleRU() string {
	if x != nil && x.TitleRU != nil {
		return *x.TitleRU
	}
	return ""
}

func (x *UpdateMovieRequest) GetTitleEN() string {
	if x != nil && x.TitleEN != nil {
		return *x.TitleEN
	}
	return ""
}

func (x *UpdateMovieRequest) GetGenresIDs() []int32 {
	if x != nil {
		return x.GenresIDs
	}
	return nil
}

func (x *UpdateMovieRequest) GetUpdateGenres() bool {
	if x != nil {
		return x.UpdateGenres
	}
	return false
}

func (x *UpdateMovieRequest) GetDuration() int32 {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return 0
}

func (x *UpdateMovieRequest) GetCountriesIDs() []int32 {
	if x != nil {
		return x.CountriesIDs
	}
	return nil
}

func (x *UpdateMovieRequest) GetUpdateCountries() bool {
	if x != nil {
		return x.UpdateCountries
	}
	return false
}

func (x *UpdateMovieRequest) GetReleaseYear() int32 {
	if x != nil && x.ReleaseYear != nil {
		return *x.ReleaseYear
	}
	return 0
}

func (x *UpdateMovieRequest) GetAgeRating() string {
	if x != nil && x.AgeRating != nil {
		return *x.AgeRating
	}
	return ""
}

type UpdateMoviePicturesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MovieID       int32  `protobuf:"varint,1,opt,name=movieID,json=movie_id,proto3" json:"movieID,omitempty"`
	PreviewPoster []byte `protobuf:"bytes,2,opt,name=previewPoster,json=preview_poster,proto3" json:"previewPoster,omitempty"`
	Poster        []byte `protobuf:"bytes,3,opt,name=poster,proto3" json:"poster,omitempty"`
	Background    []byte `protobuf:"bytes,4,opt,name=background,proto3" json:"background,omitempty"`
}

func (x *UpdateMoviePicturesRequest) Reset() {
	*x = UpdateMoviePicturesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_service_v1_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMoviePicturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMoviePicturesRequest) ProtoMessage() {}

func (x *UpdateMoviePicturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_service_v1_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMoviePicturesRequest.ProtoReflect.Descriptor instead.
func (*UpdateMoviePicturesRequest) Descriptor() ([]byte, []int) {
	return file_admin_movies_service_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateMoviePicturesRequest) GetMovieID() int32 {
	if x != nil {
		return x.MovieID
	}
	return 0
}

func (x *UpdateMoviePicturesRequest) GetPreviewPoster() []byte {
	if x != nil {
		return x.PreviewPoster
	}
	return nil
}

func (x *UpdateMoviePicturesRequest) GetPoster() []byte {
	if x != nil {
		return x.Poster
	}
	return nil
}

func (x *UpdateMoviePicturesRequest) GetBackground() []byte {
	if x != nil {
		return x.Background
	}
	return nil
}

type CreateMovieResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MovieID int32 `protobuf:"varint,1,opt,name=MovieID,json=movie_id,proto3" json:"MovieID,omitempty"`
}

func (x *CreateMovieResponce) Reset() {
	*x = CreateMovieResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_service_v1_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMovieResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMovieResponce) ProtoMessage() {}

func (x *CreateMovieResponce) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_service_v1_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMovieResponce.ProtoReflect.Descriptor instead.
func (*CreateMovieResponce) Descriptor() ([]byte, []int) {
	return file_admin_movies_service_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *CreateMovieResponce) GetMovieID() int32 {
	if x != nil {
		return x.MovieID
	}
	return 0
}

type DeleteMovieRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MovieID int32 `protobuf:"varint,1,opt,name=MovieID,json=movie_id,proto3" json:"MovieID,omitempty"`
}

func (x *DeleteMovieRequest) Reset() {
	*x = DeleteMovieRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_service_v1_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMovieRequest) ProtoMessage() {}

func (x *DeleteMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_service_v1_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMovieRequest.ProtoReflect.Descriptor instead.
func (*DeleteMovieRequest) Descriptor() ([]byte, []int) {
	return file_admin_movies_service_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteMovieRequest) GetMovieID() int32 {
	if x != nil {
		return x.MovieID
	}
	return 0
}

type IsMovieExistsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MovieID int32 `protobuf:"varint,1,opt,name=MovieID,json=movie_id,proto3" json:"MovieID,omitempty"`
}

func (x *IsMovieExistsRequest) Reset() {
	*x = IsMovieExistsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_service_v1_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsMovieExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsMovieExistsRequest) ProtoMessage() {}

func (x *IsMovieExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_service_v1_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsMovieExistsRequest.ProtoReflect.Descriptor instead.
func (*IsMovieExistsRequest) Descriptor() ([]byte, []int) {
	return file_admin_movies_service_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *IsMovieExistsRequest) GetMovieID() int32 {
	if x != nil {
		return x.MovieID
	}
	return 0
}

type IsMovieExistsResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exists bool `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
}

func (x *IsMovieExistsResponce) Reset() {
	*x = IsMovieExistsResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_service_v1_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsMovieExistsResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsMovieExistsResponce) ProtoMessage() {}

func (x *IsMovieExistsResponce) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_service_v1_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsMovieExistsResponce.ProtoReflect.Descriptor instead.
func (*IsMovieExistsResponce) Descriptor() ([]byte, []int) {
	return file_admin_movies_service_v1_messages_proto_rawDescGZIP(), []int{8}
}

func (x *IsMovieExistsResponce) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type CreateAgeRatingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgeRatingName string `protobuf:"bytes,1,opt,name=AgeRatingName,json=age_rating_name,proto3" json:"AgeRatingName,omitempty"`
}

func (x *CreateAgeRatingRequest) Reset() {
	*x = CreateAgeRatingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_service_v1_messages_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAgeRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgeRatingRequest) ProtoMessage() {}

func (x *CreateAgeRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_service_v1_messages_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgeRatingRequest.ProtoReflect.Descriptor instead.
func (*CreateAgeRatingRequest) Descriptor() ([]byte, []int) {
	return file_admin_movies_service_v1_messages_proto_rawDescGZIP(), []int{9}
}

func (x *CreateAgeRatingRequest) GetAgeRatingName() string {
	if x != nil {
		return x.AgeRatingName
	}
	return ""
}

type DeleteAgeRatingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgeRatingName string `protobuf:"bytes,1,opt,name=AgeRatingName,json=age_rating_name,proto3" json:"AgeRatingName,omitempty"`
}

func (x *DeleteAgeRatingRequest) Reset() {
	*x = DeleteAgeRatingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_service_v1_messages_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAgeRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgeRatingRequest) ProtoMessage() {}

func (x *DeleteAgeRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_service_v1_messages_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgeRatingRequest.ProtoReflect.Descriptor instead.
func (*DeleteAgeRatingRequest) Descriptor() ([]byte, []int) {
	return file_admin_movies_service_v1_messages_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteAgeRatingRequest) GetAgeRatingName() string {
	if x != nil {
		return x.AgeRatingName
	}
	return ""
}

type IsExistsResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MovieExists bool `protobuf:"varint,1,opt,name=MovieExists,json=movie_exists,proto3" json:"MovieExists,omitempty"`
}

func (x *IsExistsResponce) Reset() {
	*x = IsExistsResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_service_v1_messages_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsExistsResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsExistsResponce) ProtoMessage() {}

func (x *IsExistsResponce) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_service_v1_messages_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsExistsResponce.ProtoReflect.Descriptor instead.
func (*IsExistsResponce) Descriptor() ([]byte, []int) {
	return file_admin_movies_service_v1_messages_proto_rawDescGZIP(), []int{11}
}

func (x *IsExistsResponce) GetMovieExists() bool {
	if x != nil {
		return x.MovieExists
	}
	return false
}

type Movies struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Movies map[int32]*Movie `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Movies) Reset() {
	*x = Movies{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_service_v1_messages_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Movies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movies) ProtoMessage() {}

func (x *Movies) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_service_v1_messages_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movies.ProtoReflect.Descriptor instead.
func (*Movies) Descriptor() ([]byte, []int) {
	return file_admin_movies_service_v1_messages_proto_rawDescGZIP(), []int{12}
}

func (x *Movies) GetMovies() map[int32]*Movie {
	if x != nil {
		return x.Movies
	}
	return nil
}

type AgeRatings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ratings []string `protobuf:"bytes,1,rep,name=ratings,proto3" json:"ratings,omitempty"`
}

func (x *AgeRatings) Reset() {
	*x = AgeRatings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_service_v1_messages_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgeRatings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgeRatings) ProtoMessage() {}

func (x *AgeRatings) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_service_v1_messages_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgeRatings.ProtoReflect.Descriptor instead.
func (*AgeRatings) Descriptor() ([]byte, []int) {
	return file_admin_movies_service_v1_messages_proto_rawDescGZIP(), []int{13}
}

func (x *AgeRatings) GetRatings() []string {
	if x != nil {
		return x.Ratings
	}
	return nil
}

type GetGenreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GenreId int32 `protobuf:"varint,1,opt,name=genre_id,json=genreId,proto3" json:"genre_id,omitempty"`
}

func (x *GetGenreRequest) Reset() {
	*x = GetGenreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_service_v1_messages_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGenreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenreRequest) ProtoMessage() {}

func (x *GetGenreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_service_v1_messages_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenreRequest.ProtoReflect.Descriptor instead.
func (*GetGenreRequest) Descriptor() ([]byte, []int) {
	return file_admin_movies_service_v1_messages_proto_rawDescGZIP(), []int{14}
}

func (x *GetGenreRequest) GetGenreId() int32 {
	if x != nil {
		return x.GenreId
	}
	return 0
}

type Genre struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GenreID int32  `protobuf:"varint,1,opt,name=GenreID,json=genre_id,proto3" json:"GenreID,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
}

func (x *Genre) Reset() {
	*x = Genre{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_service_v1_messages_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Genre) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Genre) ProtoMessage() {}

func (x *Genre) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_service_v1_messages_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Genre.ProtoReflect.Descriptor instead.
func (*Genre) Descriptor() ([]byte, []int) {
	return file_admin_movies_service_v1_messages_proto_rawDescGZIP(), []int{15}
}

func (x *Genre) GetGenreID() int32 {
	if x != nil {
		return x.GenreID
	}
	return 0
}

func (x *Genre) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Genres struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Genres []*Genre `protobuf:"bytes,1,rep,name=genres,proto3" json:"genres,omitempty"`
}

func (x *Genres) Reset() {
	*x = Genres{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_service_v1_messages_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Genres) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Genres) ProtoMessage() {}

func (x *Genres) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_service_v1_messages_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Genres.ProtoReflect.Descriptor instead.
func (*Genres) Descriptor() ([]byte, []int) {
	return file_admin_movies_service_v1_messages_proto_rawDescGZIP(), []int{16}
}

func (x *Genres) GetGenres() []*Genre {
	if x != nil {
		return x.Genres
	}
	return nil
}

type CreateGenreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
}

func (x *CreateGenreRequest) Reset() {
	*x = CreateGenreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_service_v1_messages_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGenreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGenreRequest) ProtoMessage() {}

func (x *CreateGenreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_service_v1_messages_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGenreRequest.ProtoReflect.Descriptor instead.
func (*CreateGenreRequest) Descriptor() ([]byte, []int) {
	return file_admin_movies_service_v1_messages_proto_rawDescGZIP(), []int{17}
}

func (x *CreateGenreRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateGenreResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GenreID int32 `protobuf:"varint,1,opt,name=GenreID,json=genre_id,proto3" json:"GenreID,omitempty"`
}

func (x *CreateGenreResponce) Reset() {
	*x = CreateGenreResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_service_v1_messages_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGenreResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGenreResponce) ProtoMessage() {}

func (x *CreateGenreResponce) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_service_v1_messages_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGenreResponce.ProtoReflect.Descriptor instead.
func (*CreateGenreResponce) Descriptor() ([]byte, []int) {
	return file_admin_movies_service_v1_messages_proto_rawDescGZIP(), []int{18}
}

func (x *CreateGenreResponce) GetGenreID() int32 {
	if x != nil {
		return x.GenreID
	}
	return 0
}

type UpdateGenreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GenreID int32  `protobuf:"varint,1,opt,name=GenreID,json=genre_id,proto3" json:"GenreID,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
}

func (x *UpdateGenreRequest) Reset() {
	*x = UpdateGenreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_service_v1_messages_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGenreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGenreRequest) ProtoMessage() {}

func (x *UpdateGenreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_service_v1_messages_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGenreRequest.ProtoReflect.Descriptor instead.
func (*UpdateGenreRequest) Descriptor() ([]byte, []int) {
	return file_admin_movies_service_v1_messages_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateGenreRequest) GetGenreID() int32 {
	if x != nil {
		return x.GenreID
	}
	return 0
}

func (x *UpdateGenreRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetGenreByNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetGenreByNameRequest) Reset() {
	*x = GetGenreByNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_service_v1_messages_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGenreByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenreByNameRequest) ProtoMessage() {}

func (x *GetGenreByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_service_v1_messages_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenreByNameRequest.ProtoReflect.Descriptor instead.
func (*GetGenreByNameRequest) Descriptor() ([]byte, []int) {
	return file_admin_movies_service_v1_messages_proto_rawDescGZIP(), []int{20}
}

func (x *GetGenreByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteGenreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GenreId int32 `protobuf:"varint,1,opt,name=genre_id,json=genreId,proto3" json:"genre_id,omitempty"`
}

func (x *DeleteGenreRequest) Reset() {
	*x = DeleteGenreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_service_v1_messages_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGenreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGenreRequest) ProtoMessage() {}

func (x *DeleteGenreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_service_v1_messages_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGenreRequest.ProtoReflect.Descriptor instead.
func (*DeleteGenreRequest) Descriptor() ([]byte, []int) {
	return file_admin_movies_service_v1_messages_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteGenreRequest) GetGenreId() int32 {
	if x != nil {
		return x.GenreId
	}
	return 0
}

type IsGenresExistsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// use ',' as separator for multiple ids
	GenresIDs string `protobuf:"bytes,1,opt,name=GenresIDs,json=genres_ids,proto3" json:"GenresIDs,omitempty"`
}

func (x *IsGenresExistsRequest) Reset() {
	*x = IsGenresExistsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_service_v1_messages_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsGenresExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsGenresExistsRequest) ProtoMessage() {}

func (x *IsGenresExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_service_v1_messages_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsGenresExistsRequest.ProtoReflect.Descriptor instead.
func (*IsGenresExistsRequest) Descriptor() ([]byte, []int) {
	return file_admin_movies_service_v1_messages_proto_rawDescGZIP(), []int{22}
}

func (x *IsGenresExistsRequest) GetGenresIDs() string {
	if x != nil {
		return x.GenresIDs
	}
	return ""
}

type ExistsResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exists      bool    `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	NotExistIDs []int32 `protobuf:"varint,2,rep,packed,name=NotExistIDs,json=not_exists_ids,proto3" json:"NotExistIDs,omitempty"`
}

func (x *ExistsResponce) Reset() {
	*x = ExistsResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_service_v1_messages_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExistsResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsResponce) ProtoMessage() {}

func (x *ExistsResponce) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_service_v1_messages_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsResponce.ProtoReflect.Descriptor instead.
func (*ExistsResponce) Descriptor() ([]byte, []int) {
	return file_admin_movies_service_v1_messages_proto_rawDescGZIP(), []int{23}
}

func (x *ExistsResponce) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *ExistsResponce) GetNotExistIDs() []int32 {
	if x != nil {
		return x.NotExistIDs
	}
	return nil
}

type Movie struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description      string   `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	ShortDescription string   `protobuf:"bytes,2,opt,name=shortDescription,json=short_description,proto3" json:"shortDescription,omitempty"`
	TitleRU          string   `protobuf:"bytes,3,opt,name=titleRU,json=title_ru,proto3" json:"titleRU,omitempty"`
	TitleEN          string   `protobuf:"bytes,4,opt,name=titleEN,json=title_en,proto3" json:"titleEN,omitempty"`
	Genres           []string `protobuf:"bytes,5,rep,name=genres,proto3" json:"genres,omitempty"`
	// movie duration in minutes
	Duration         int32    `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`
	Countries        []string `protobuf:"bytes,7,rep,name=countries,proto3" json:"countries,omitempty"`
	PosterURL        string   `protobuf:"bytes,8,opt,name=posterURL,json=poster_url,proto3" json:"posterURL,omitempty"`
	PreviewPosterURL string   `protobuf:"bytes,9,opt,name=previewPosterURL,json=preview_poster_url,proto3" json:"previewPosterURL,omitempty"`
	BackgroundURL    string   `protobuf:"bytes,10,opt,name=backgroundURL,json=background_url,proto3" json:"backgroundURL,omitempty"`
	ReleaseYear      int32    `protobuf:"varint,11,opt,name=releaseYear,json=release_year,proto3" json:"releaseYear,omitempty"`
	AgeRating        string   `protobuf:"bytes,12,opt,name=ageRating,json=age_rating,proto3" json:"ageRating,omitempty"`
}

func (x *Movie) Reset() {
	*x = Movie{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_service_v1_messages_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Movie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movie) ProtoMessage() {}

func (x *Movie) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_service_v1_messages_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movie.ProtoReflect.Descriptor instead.
func (*Movie) Descriptor() ([]byte, []int) {
	return file_admin_movies_service_v1_messages_proto_rawDescGZIP(), []int{24}
}

func (x *Movie) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Movie) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *Movie) GetTitleRU() string {
	if x != nil {
		return x.TitleRU
	}
	return ""
}

func (x *Movie) GetTitleEN() string {
	if x != nil {
		return x.TitleEN
	}
	return ""
}

func (x *Movie) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *Movie) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Movie) GetCountries() []string {
	if x != nil {
		return x.Countries
	}
	return nil
}

func (x *Movie) GetPosterURL() string {
	if x != nil {
		return x.PosterURL
	}
	return ""
}

func (x *Movie) GetPreviewPosterURL() string {
	if x != nil {
		return x.PreviewPosterURL
	}
	return ""
}

func (x *Movie) GetBackgroundURL() string {
	if x != nil {
		return x.BackgroundURL
	}
	return ""
}

func (x *Movie) GetReleaseYear() int32 {
	if x != nil {
		return x.ReleaseYear
	}
	return 0
}

func (x *Movie) GetAgeRating() string {
	if x != nil {
		return x.AgeRating
	}
	return ""
}

type GetCountryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CountryId int32 `protobuf:"varint,1,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
}

func (x *GetCountryRequest) Reset() {
	*x = GetCountryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_service_v1_messages_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCountryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCountryRequest) ProtoMessage() {}

func (x *GetCountryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_service_v1_messages_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCountryRequest.ProtoReflect.Descriptor instead.
func (*GetCountryRequest) Descriptor() ([]byte, []int) {
	return file_admin_movies_service_v1_messages_proto_rawDescGZIP(), []int{25}
}

func (x *GetCountryRequest) GetCountryId() int32 {
	if x != nil {
		return x.CountryId
	}
	return 0
}

type Country struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CountryID int32  `protobuf:"varint,1,opt,name=CountryID,json=country_id,proto3" json:"CountryID,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
}

func (x *Country) Reset() {
	*x = Country{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_service_v1_messages_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Country) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Country) ProtoMessage() {}

func (x *Country) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_service_v1_messages_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Country.ProtoReflect.Descriptor instead.
func (*Country) Descriptor() ([]byte, []int) {
	return file_admin_movies_service_v1_messages_proto_rawDescGZIP(), []int{26}
}

func (x *Country) GetCountryID() int32 {
	if x != nil {
		return x.CountryID
	}
	return 0
}

func (x *Country) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Countries struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Countries []*Country `protobuf:"bytes,1,rep,name=countries,proto3" json:"countries,omitempty"`
}

func (x *Countries) Reset() {
	*x = Countries{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_service_v1_messages_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Countries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Countries) ProtoMessage() {}

func (x *Countries) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_service_v1_messages_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Countries.ProtoReflect.Descriptor instead.
func (*Countries) Descriptor() ([]byte, []int) {
	return file_admin_movies_service_v1_messages_proto_rawDescGZIP(), []int{27}
}

func (x *Countries) GetCountries() []*Country {
	if x != nil {
		return x.Countries
	}
	return nil
}

type CreateCountryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
}

func (x *CreateCountryRequest) Reset() {
	*x = CreateCountryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_service_v1_messages_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCountryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCountryRequest) ProtoMessage() {}

func (x *CreateCountryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_service_v1_messages_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCountryRequest.ProtoReflect.Descriptor instead.
func (*CreateCountryRequest) Descriptor() ([]byte, []int) {
	return file_admin_movies_service_v1_messages_proto_rawDescGZIP(), []int{28}
}

func (x *CreateCountryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateCountryResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CountryID int32 `protobuf:"varint,1,opt,name=CountryID,json=country_id,proto3" json:"CountryID,omitempty"`
}

func (x *CreateCountryResponce) Reset() {
	*x = CreateCountryResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_service_v1_messages_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCountryResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCountryResponce) ProtoMessage() {}

func (x *CreateCountryResponce) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_service_v1_messages_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCountryResponce.ProtoReflect.Descriptor instead.
func (*CreateCountryResponce) Descriptor() ([]byte, []int) {
	return file_admin_movies_service_v1_messages_proto_rawDescGZIP(), []int{29}
}

func (x *CreateCountryResponce) GetCountryID() int32 {
	if x != nil {
		return x.CountryID
	}
	return 0
}

type GetCountryByNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetCountryByNameRequest) Reset() {
	*x = GetCountryByNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_service_v1_messages_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCountryByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCountryByNameRequest) ProtoMessage() {}

func (x *GetCountryByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_service_v1_messages_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCountryByNameRequest.ProtoReflect.Descriptor instead.
func (*GetCountryByNameRequest) Descriptor() ([]byte, []int) {
	return file_admin_movies_service_v1_messages_proto_rawDescGZIP(), []int{30}
}

func (x *GetCountryByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteCountryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CountryId int32 `protobuf:"varint,1,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
}

func (x *DeleteCountryRequest) Reset() {
	*x = DeleteCountryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_service_v1_messages_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCountryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCountryRequest) ProtoMessage() {}

func (x *DeleteCountryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_service_v1_messages_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCountryRequest.ProtoReflect.Descriptor instead.
func (*DeleteCountryRequest) Descriptor() ([]byte, []int) {
	return file_admin_movies_service_v1_messages_proto_rawDescGZIP(), []int{31}
}

func (x *DeleteCountryRequest) GetCountryId() int32 {
	if x != nil {
		return x.CountryId
	}
	return 0
}

type IsCountriesExistsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// use ',' as separator for multiple ids
	CountriesIDs string `protobuf:"bytes,1,opt,name=CountriesIDs,json=countries_ids,proto3" json:"CountriesIDs,omitempty"`
}

func (x *IsCountriesExistsRequest) Reset() {
	*x = IsCountriesExistsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_service_v1_messages_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsCountriesExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsCountriesExistsRequest) ProtoMessage() {}

func (x *IsCountriesExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_service_v1_messages_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsCountriesExistsRequest.ProtoReflect.Descriptor instead.
func (*IsCountriesExistsRequest) Descriptor() ([]byte, []int) {
	return file_admin_movies_service_v1_messages_proto_rawDescGZIP(), []int{32}
}

func (x *IsCountriesExistsRequest) GetCountriesIDs() string {
	if x != nil {
		return x.CountriesIDs
	}
	return ""
}

type UpdateCountryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CountryID int32  `protobuf:"varint,1,opt,name=CountryID,json=country_id,proto3" json:"CountryID,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
}

func (x *UpdateCountryRequest) Reset() {
	*x = UpdateCountryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_service_v1_messages_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCountryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCountryRequest) ProtoMessage() {}

func (x *UpdateCountryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_service_v1_messages_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCountryRequest.ProtoReflect.Descriptor instead.
func (*UpdateCountryRequest) Descriptor() ([]byte, []int) {
	return file_admin_movies_service_v1_messages_proto_rawDescGZIP(), []int{33}
}

func (x *UpdateCountryRequest) GetCountryID() int32 {
	if x != nil {
		return x.CountryID
	}
	return 0
}

func (x *UpdateCountryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UserErrorMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UserErrorMessage) Reset() {
	*x = UserErrorMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_service_v1_messages_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserErrorMessage) ProtoMessage() {}

func (x *UserErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_service_v1_messages_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserErrorMessage.ProtoReflect.Descriptor instead.
func (*UserErrorMessage) Descriptor() ([]byte, []int) {
	return file_admin_movies_service_v1_messages_proto_rawDescGZIP(), []int{34}
}

func (x *UserErrorMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_admin_movies_service_v1_messages_proto protoreflect.FileDescriptor

var file_admin_movies_service_v1_messages_proto_rawDesc = []byte{
	0x0a, 0x26, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x76, 0x31, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f,
	0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x2c,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x19, 0x0a, 0x07, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x69, 0x64, 0x22, 0xb7, 0x02, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x22, 0x0a, 0x09, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x49, 0x44, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0a, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x5f, 0x69,
	0x64, 0x73, 0x88, 0x01, 0x01, 0x12, 0x22, 0x0a, 0x09, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x49,
	0x44, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0a, 0x67, 0x65, 0x6e, 0x72,
	0x65, 0x73, 0x5f, 0x69, 0x64, 0x73, 0x88, 0x01, 0x01, 0x12, 0x26, 0x0a, 0x0c, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x49, 0x44, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x02, 0x52, 0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x73, 0x88, 0x01,
	0x01, 0x12, 0x19, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x03, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x12, 0x24, 0x0a, 0x0a,
	0x61, 0x67, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x04, 0x52, 0x0b, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x88,
	0x01, 0x01, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x49, 0x44, 0x73, 0x42, 0x0c,
	0x0a, 0x0a, 0x5f, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x49, 0x44, 0x73, 0x42, 0x0f, 0x0a, 0x0d,
	0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x49, 0x44, 0x73, 0x42, 0x08, 0x0a,
	0x06, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x61, 0x67, 0x65, 0x52,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x22, 0xa9, 0x03, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x2b, 0x0a, 0x10, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x07,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x52, 0x55, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x5f, 0x72, 0x75, 0x12, 0x1e, 0x0a, 0x07, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x45, 0x4e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x5f, 0x65, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x09, 0x67, 0x65, 0x6e, 0x72, 0x65,
	0x73, 0x49, 0x44, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0a, 0x67, 0x65, 0x6e, 0x72,
	0x65, 0x73, 0x5f, 0x69, 0x64, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x49,
	0x44, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72,
	0x79, 0x5f, 0x69, 0x64, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x12, 0x25, 0x0a,
	0x0d, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x50, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x70, 0x6f,
	0x73, 0x74, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75,
	0x6e, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72,
	0x6f, 0x75, 0x6e, 0x64, 0x12, 0x21, 0x0a, 0x0b, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x59,
	0x65, 0x61, 0x72, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x72, 0x65, 0x6c, 0x65, 0x61,
	0x73, 0x65, 0x5f, 0x79, 0x65, 0x61, 0x72, 0x12, 0x1d, 0x0a, 0x09, 0x61, 0x67, 0x65, 0x52, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x67, 0x65, 0x5f,
	0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x45, 0x4e, 0x22, 0xb1, 0x04, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x76,
	0x69, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x07, 0x6d, 0x6f, 0x76,
	0x69, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x6f, 0x76, 0x69,
	0x65, 0x5f, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x30, 0x0a, 0x10, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x11, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x1e, 0x0a,
	0x07, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x52, 0x55, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02,
	0x52, 0x08, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x5f, 0x72, 0x75, 0x88, 0x01, 0x01, 0x12, 0x1e, 0x0a,
	0x07, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x45, 0x4e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03,
	0x52, 0x08, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x5f, 0x65, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a,
	0x09, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x49, 0x44, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x05,
	0x52, 0x0a, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x5f, 0x69, 0x64, 0x73, 0x12, 0x23, 0x0a, 0x0c,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0d, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x67, 0x65, 0x6e, 0x72, 0x65,
	0x73, 0x12, 0x1f, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x05, 0x48, 0x04, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x88,
	0x01, 0x01, 0x12, 0x23, 0x0a, 0x0c, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x49,
	0x44, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0d, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72,
	0x69, 0x65, 0x73, 0x5f, 0x69, 0x64, 0x73, 0x12, 0x29, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x10, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x69,
	0x65, 0x73, 0x12, 0x26, 0x0a, 0x0b, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x59, 0x65, 0x61,
	0x72, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x48, 0x05, 0x52, 0x0c, 0x72, 0x65, 0x6c, 0x65, 0x61,
	0x73, 0x65, 0x5f, 0x79, 0x65, 0x61, 0x72, 0x88, 0x01, 0x01, 0x12, 0x22, 0x0a, 0x09, 0x61, 0x67,
	0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x48, 0x06, 0x52,
	0x0a, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x88, 0x01, 0x01, 0x42, 0x0e,
	0x0a, 0x0c, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x13,
	0x0a, 0x11, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x52, 0x55, 0x42,
	0x0a, 0x0a, 0x08, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x45, 0x4e, 0x42, 0x0b, 0x0a, 0x09, 0x5f,
	0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x72, 0x65, 0x6c,
	0x65, 0x61, 0x73, 0x65, 0x59, 0x65, 0x61, 0x72, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x61, 0x67, 0x65,
	0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x96, 0x01, 0x0a, 0x1a, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x07, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x69, 0x64,
	0x12, 0x25, 0x0a, 0x0d, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x50, 0x6f, 0x73, 0x74, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77,
	0x5f, 0x70, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x12,
	0x1e, 0x0a, 0x0a, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0a, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x22,
	0x30, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x19, 0x0a, 0x07, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x69,
	0x64, 0x22, 0x2f, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x07, 0x4d, 0x6f, 0x76, 0x69, 0x65,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f,
	0x69, 0x64, 0x22, 0x31, 0x0a, 0x14, 0x49, 0x73, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x45, 0x78, 0x69,
	0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x07, 0x4d, 0x6f,
	0x76, 0x69, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x6f, 0x76,
	0x69, 0x65, 0x5f, 0x69, 0x64, 0x22, 0x2f, 0x0a, 0x15, 0x49, 0x73, 0x4d, 0x6f, 0x76, 0x69, 0x65,
	0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x22, 0x40, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x41, 0x67, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x26, 0x0a, 0x0d, 0x41, 0x67, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x40, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x41, 0x67, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x26, 0x0a, 0x0d, 0x41, 0x67, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x61, 0x67, 0x65, 0x5f, 0x72,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x35, 0x0a, 0x10, 0x49, 0x73,
	0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x21,
	0x0a, 0x0b, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0c, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x65, 0x78, 0x69, 0x73, 0x74,
	0x73, 0x22, 0xa2, 0x01, 0x0a, 0x06, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x12, 0x40, 0x0a, 0x06,
	0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x1a, 0x56,
	0x0a, 0x0b, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x31, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x26, 0x0a, 0x0a, 0x41, 0x67, 0x65, 0x52, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x2c,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x49, 0x64, 0x22, 0x36, 0x0a, 0x05,
	0x47, 0x65, 0x6e, 0x72, 0x65, 0x12, 0x19, 0x0a, 0x07, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x5f, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3d, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x12, 0x33,
	0x0a, 0x06, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x52, 0x06, 0x67, 0x65, 0x6e,
	0x72, 0x65, 0x73, 0x22, 0x28, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x65, 0x6e,
	0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x30, 0x0a,
	0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x63, 0x65, 0x12, 0x19, 0x0a, 0x07, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x5f, 0x69, 0x64, 0x22,
	0x43, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x07, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x5f, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2b, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x47, 0x65, 0x6e, 0x72, 0x65,
	0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x2f, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x65, 0x6e, 0x72, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x65, 0x6e, 0x72, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x67, 0x65, 0x6e, 0x72, 0x65,
	0x49, 0x64, 0x22, 0x36, 0x0a, 0x15, 0x49, 0x73, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x45, 0x78,
	0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x09, 0x47,
	0x65, 0x6e, 0x72, 0x65, 0x73, 0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x5f, 0x69, 0x64, 0x73, 0x22, 0x4d, 0x0a, 0x0e, 0x45, 0x78,
	0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x78,
	0x69, 0x73, 0x74, 0x73, 0x12, 0x23, 0x0a, 0x0b, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74,
	0x49, 0x44, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0e, 0x6e, 0x6f, 0x74, 0x5f, 0x65,
	0x78, 0x69, 0x73, 0x74, 0x73, 0x5f, 0x69, 0x64, 0x73, 0x22, 0x94, 0x03, 0x0a, 0x05, 0x4d, 0x6f,
	0x76, 0x69, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2b, 0x0a, 0x10, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x11, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x07, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x52, 0x55, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x5f, 0x72, 0x75, 0x12, 0x19, 0x0a,
	0x07, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x45, 0x4e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x5f, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x72,
	0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x09, 0x70, 0x6f,
	0x73, 0x74, 0x65, 0x72, 0x55, 0x52, 0x4c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70,
	0x6f, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x75, 0x72, 0x6c, 0x12, 0x2c, 0x0a, 0x10, 0x70, 0x72, 0x65,
	0x76, 0x69, 0x65, 0x77, 0x50, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x55, 0x52, 0x4c, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x12, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x70, 0x6f, 0x73,
	0x74, 0x65, 0x72, 0x5f, 0x75, 0x72, 0x6c, 0x12, 0x25, 0x0a, 0x0d, 0x62, 0x61, 0x63, 0x6b, 0x67,
	0x72, 0x6f, 0x75, 0x6e, 0x64, 0x55, 0x52, 0x4c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x75, 0x72, 0x6c, 0x12, 0x21,
	0x0a, 0x0b, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x59, 0x65, 0x61, 0x72, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0c, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x79, 0x65, 0x61,
	0x72, 0x12, 0x1d, 0x0a, 0x09, 0x61, 0x67, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x22, 0x32, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x72, 0x79, 0x49, 0x64, 0x22, 0x3c, 0x0a, 0x07, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x1d, 0x0a, 0x09, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x48, 0x0a, 0x09, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12,
	0x3b, 0x0a, 0x09, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x6d, 0x6f, 0x76, 0x69, 0x65,
	0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x09, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0x2a, 0x0a, 0x14,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x36, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63,
	0x65, 0x12, 0x1d, 0x0a, 0x09, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x69, 0x64,
	0x22, 0x2d, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x42, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x35, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x72, 0x79, 0x49, 0x64, 0x22, 0x3f, 0x0a, 0x18, 0x49, 0x73, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x72, 0x69, 0x65, 0x73, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x23, 0x0a, 0x0c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x49,
	0x44, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72,
	0x69, 0x65, 0x73, 0x5f, 0x69, 0x64, 0x73, 0x22, 0x49, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1d, 0x0a, 0x09, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x2c, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x42, 0x20, 0x5a, 0x1e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_admin_movies_service_v1_messages_proto_rawDescOnce sync.Once
	file_admin_movies_service_v1_messages_proto_rawDescData = file_admin_movies_service_v1_messages_proto_rawDesc
)

func file_admin_movies_service_v1_messages_proto_rawDescGZIP() []byte {
	file_admin_movies_service_v1_messages_proto_rawDescOnce.Do(func() {
		file_admin_movies_service_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_admin_movies_service_v1_messages_proto_rawDescData)
	})
	return file_admin_movies_service_v1_messages_proto_rawDescData
}

var file_admin_movies_service_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_admin_movies_service_v1_messages_proto_goTypes = []interface{}{
	(*GetMovieRequest)(nil),            // 0: admin_movies_service.GetMovieRequest
	(*GetMoviesRequest)(nil),           // 1: admin_movies_service.GetMoviesRequest
	(*CreateMovieRequest)(nil),         // 2: admin_movies_service.CreateMovieRequest
	(*UpdateMovieRequest)(nil),         // 3: admin_movies_service.UpdateMovieRequest
	(*UpdateMoviePicturesRequest)(nil), // 4: admin_movies_service.UpdateMoviePicturesRequest
	(*CreateMovieResponce)(nil),        // 5: admin_movies_service.CreateMovieResponce
	(*DeleteMovieRequest)(nil),         // 6: admin_movies_service.DeleteMovieRequest
	(*IsMovieExistsRequest)(nil),       // 7: admin_movies_service.IsMovieExistsRequest
	(*IsMovieExistsResponce)(nil),      // 8: admin_movies_service.IsMovieExistsResponce
	(*CreateAgeRatingRequest)(nil),     // 9: admin_movies_service.CreateAgeRatingRequest
	(*DeleteAgeRatingRequest)(nil),     // 10: admin_movies_service.DeleteAgeRatingRequest
	(*IsExistsResponce)(nil),           // 11: admin_movies_service.IsExistsResponce
	(*Movies)(nil),                     // 12: admin_movies_service.Movies
	(*AgeRatings)(nil),                 // 13: admin_movies_service.AgeRatings
	(*GetGenreRequest)(nil),            // 14: admin_movies_service.GetGenreRequest
	(*Genre)(nil),                      // 15: admin_movies_service.Genre
	(*Genres)(nil),                     // 16: admin_movies_service.Genres
	(*CreateGenreRequest)(nil),         // 17: admin_movies_service.CreateGenreRequest
	(*CreateGenreResponce)(nil),        // 18: admin_movies_service.CreateGenreResponce
	(*UpdateGenreRequest)(nil),         // 19: admin_movies_service.UpdateGenreRequest
	(*GetGenreByNameRequest)(nil),      // 20: admin_movies_service.GetGenreByNameRequest
	(*DeleteGenreRequest)(nil),         // 21: admin_movies_service.DeleteGenreRequest
	(*IsGenresExistsRequest)(nil),      // 22: admin_movies_service.IsGenresExistsRequest
	(*ExistsResponce)(nil),             // 23: admin_movies_service.ExistsResponce
	(*Movie)(nil),                      // 24: admin_movies_service.Movie
	(*GetCountryRequest)(nil),          // 25: admin_movies_service.GetCountryRequest
	(*Country)(nil),                    // 26: admin_movies_service.Country
	(*Countries)(nil),                  // 27: admin_movies_service.Countries
	(*CreateCountryRequest)(nil),       // 28: admin_movies_service.CreateCountryRequest
	(*CreateCountryResponce)(nil),      // 29: admin_movies_service.CreateCountryResponce
	(*GetCountryByNameRequest)(nil),    // 30: admin_movies_service.GetCountryByNameRequest
	(*DeleteCountryRequest)(nil),       // 31: admin_movies_service.DeleteCountryRequest
	(*IsCountriesExistsRequest)(nil),   // 32: admin_movies_service.IsCountriesExistsRequest
	(*UpdateCountryRequest)(nil),       // 33: admin_movies_service.UpdateCountryRequest
	(*UserErrorMessage)(nil),           // 34: admin_movies_service.UserErrorMessage
	nil,                                // 35: admin_movies_service.Movies.MoviesEntry
}
var file_admin_movies_service_v1_messages_proto_depIdxs = []int32{
	35, // 0: admin_movies_service.Movies.movies:type_name -> admin_movies_service.Movies.MoviesEntry
	15, // 1: admin_movies_service.Genres.genres:type_name -> admin_movies_service.Genre
	26, // 2: admin_movies_service.Countries.countries:type_name -> admin_movies_service.Country
	24, // 3: admin_movies_service.Movies.MoviesEntry.value:type_name -> admin_movies_service.Movie
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_admin_movies_service_v1_messages_proto_init() }
func file_admin_movies_service_v1_messages_proto_init() {
	if File_admin_movies_service_v1_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_admin_movies_service_v1_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMovieRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_service_v1_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMoviesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_service_v1_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMovieRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_service_v1_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMovieRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_service_v1_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMoviePicturesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_service_v1_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMovieResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_service_v1_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMovieRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_service_v1_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsMovieExistsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_service_v1_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsMovieExistsResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_service_v1_messages_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAgeRatingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_service_v1_messages_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAgeRatingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_service_v1_messages_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsExistsResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_service_v1_messages_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Movies); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_service_v1_messages_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgeRatings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_service_v1_messages_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGenreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_service_v1_messages_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Genre); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_service_v1_messages_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Genres); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_service_v1_messages_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGenreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_service_v1_messages_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGenreResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_service_v1_messages_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGenreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_service_v1_messages_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGenreByNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_service_v1_messages_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGenreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_service_v1_messages_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsGenresExistsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_service_v1_messages_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExistsResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_service_v1_messages_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Movie); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_service_v1_messages_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCountryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_service_v1_messages_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Country); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_service_v1_messages_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Countries); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_service_v1_messages_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCountryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_service_v1_messages_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCountryResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_service_v1_messages_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCountryByNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_service_v1_messages_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCountryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_service_v1_messages_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsCountriesExistsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_service_v1_messages_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCountryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_service_v1_messages_proto_msgTypes[34].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserErrorMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_admin_movies_service_v1_messages_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_admin_movies_service_v1_messages_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_admin_movies_service_v1_messages_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_admin_movies_service_v1_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_admin_movies_service_v1_messages_proto_goTypes,
		DependencyIndexes: file_admin_movies_service_v1_messages_proto_depIdxs,
		MessageInfos:      file_admin_movies_service_v1_messages_proto_msgTypes,
	}.Build()
	File_admin_movies_service_v1_messages_proto = out.File
	file_admin_movies_service_v1_messages_proto_rawDesc = nil
	file_admin_movies_service_v1_messages_proto_goTypes = nil
	file_admin_movies_service_v1_messages_proto_depIdxs = nil
}
